"""Product backlog for the Attendance Management System (from SRS FR-01..FR-15, NFR-01..NFR-06, UC-01..UC-07)."""

PROJECT_TITLE = "Attendance Management System – Product Backlog"

SPRINTS = {
    1: dict(title="Sprint 1", goal="Foundation: login, class setup and core attendance marking", due="2026-10-14T23:59:59Z"),
    2: dict(title="Sprint 2", goal="Viewing, percentage calculation, reports and user administration", due="2026-10-28T23:59:59Z"),
    3: dict(title="Sprint 3", goal="Search, alerts, export, dashboard, security hardening and quality (NFRs)", due="2026-11-11T23:59:59Z"),
}

# id, title, color, requirements
EPICS = [
    ("E1", "Authentication & Access Control", "5319E7", "FR-01, FR-13, FR-15, NFR-01"),
    ("E2", "Attendance Marking & Records",    "1D76DB", "FR-02, FR-03"),
    ("E3", "Attendance Viewing & Search",     "0E8A16", "FR-05, FR-10"),
    ("E4", "Percentage & Alerts",             "FBCA04", "FR-04, FR-11"),
    ("E5", "Reporting",                       "D93F0B", "FR-06, FR-12"),
    ("E6", "Administration",                  "C5DEF5", "FR-07, FR-08, FR-09"),
    ("E7", "Dashboard",                       "BFD4F2", "FR-14"),
    ("E8", "Quality & Non-Functional",        "B60205", "NFR-01 to NFR-06"),
]

# id, epic, title, story, criteria, points, priority, sprint, requirement, use case
STORIES = [
 ("US-01","E1","Log in with role-based access",
  "As an Administrator, Teacher or Student, I want to log in with my ID and password so that I reach the dashboard for my role.",
  ["Valid credentials open the dashboard that matches the user's role",
   "Credentials are verified through the Security / Auth Service, which returns the role",
   "A session is created only after successful verification"],
  5,"High",1,"FR-01","UC-01"),
 ("US-02","E1","Handle invalid credentials and locked accounts",
  "As a user, I want clear messages when login fails so that I know what to do next.",
  ["Invalid credentials show an error and ask the user to re-enter",
   "A locked or disabled account is denied and told to contact the administrator",
   "No session is created on failure"],
  3,"High",1,"FR-01","UC-01 (alt 3a, 4a)"),
 ("US-03","E1","Log out securely",
  "As a logged-in user, I want to log out so that nobody else can use my session.",
  ["Logout ends the active session and returns to the login page",
   "Pressing Back does not reopen protected pages"],
  2,"Low",3,"FR-15",""),
 ("US-04","E1","Change my password",
  "As a logged-in user, I want to change my password so that I can keep my account secure.",
  ["User must enter the current password to set a new one",
   "New password is validated and a confirmation is shown"],
  3,"Low",3,"FR-13",""),
 ("US-05","E1","Restrict pages and data by role",
  "As a Student, I want to see only my own attendance so that my data stays private.",
  ["A Student cannot open another student's records, even by typing a URL",
   "A Teacher can access only their assigned classes and subjects",
   "User management pages are available only to the Administrator"],
  5,"High",2,"NFR-01","UC-01, UC-05"),
 ("US-06","E2","Select class, subject and date",
  "As a Teacher, I want to pick a class, subject and date so that I can mark attendance for that session.",
  ["Only classes and subjects assigned to the Teacher are listed",
   "A message is shown when no classes are assigned",
   "The student roster loads for the chosen class, subject and date"],
  3,"High",1,"FR-02","UC-02"),
 ("US-07","E2","Mark Present, Absent or Late",
  "As a Teacher, I want to mark each student Present, Absent or Late so that the day's attendance is recorded.",
  ["Each student can be set to Present, Absent or Late",
   "Submitting with an unmarked student prompts the Teacher to complete all entries",
   "Teacher can review the marks before submitting"],
  5,"High",1,"FR-02","UC-03"),
 ("US-08","E2","Save attendance records",
  "As a Teacher, I want submitted attendance to be saved so that it is stored permanently.",
  ["Submitted attendance is stored in the Attendance Database",
   "A success confirmation is shown to the Teacher",
   "Saving triggers recalculation of the attendance percentage"],
  5,"High",1,"FR-03","UC-04"),
 ("US-09","E2","Prevent duplicate attendance and allow updates",
  "As a Teacher, I want the system to stop duplicate entries and let me correct a record so that data stays accurate.",
  ["A second record for the same student, subject and date cannot be created",
   "An authorized Teacher can update the existing record instead",
   "The update is confirmed to the Teacher"],
  5,"High",1,"FR-03","UC-04"),
 ("US-10","E2","Keep entered data when a save fails",
  "As a Teacher, I want my marks kept if saving fails so that I do not have to enter them again.",
  ["A failed save shows an error and a retry option",
   "Marks already entered are not lost",
   "No partial records are written"],
  3,"Medium",3,"NFR-03","UC-04 (alt 3a)"),
 ("US-11","E3","View my attendance as a student",
  "As a Student, I want to view my attendance by subject and date so that I know where I stand.",
  ["Records can be filtered by subject and date",
   "The attendance percentage is shown with the records",
   "A message is shown when no records exist"],
  5,"High",2,"FR-05","UC-05"),
 ("US-12","E3","View class attendance as a teacher",
  "As a Teacher, I want to view attendance for my classes so that I can follow my students' attendance.",
  ["Teacher can view records by class, subject and date",
   "Only the Teacher's own classes are visible"],
  3,"High",2,"FR-05","UC-05"),
 ("US-13","E3","Search and filter attendance records",
  "As an authorized user, I want to search and filter records so that I can find specific attendance quickly.",
  ["Filter by student, subject, class or date",
   "Results update to match the selected filters"],
  3,"Medium",3,"FR-10","UC-05"),
 ("US-14","E4","Calculate attendance percentage automatically",
  "As a Student or Teacher, I want the system to calculate attendance percentage so that I do not have to do it by hand.",
  ["Percentage = classes attended / total classes held, per subject",
   "The rule for counting Late is decided by the team and documented",
   "Shows 0% or N/A when no records exist, and updates after every save"],
  5,"High",2,"FR-04","UC-06"),
 ("US-15","E4","Alert on low attendance",
  "As a Teacher, I want to see students whose attendance is below a threshold so that I can follow them up.",
  ["Threshold can be set by an authorized user",
   "Students below the threshold are listed"],
  3,"Medium",3,"FR-11",""),
 ("US-16","E5","Generate attendance reports",
  "As a Teacher or Administrator, I want reports by student, class, subject or date range so that I can review attendance.",
  ["Report scope can be student, class, subject or date range",
   "Report is compiled through the Report Engine",
   "A message is shown when no data exists for the scope",
   "Report loads within 3 seconds under normal conditions"],
  8,"High",2,"FR-06","UC-07"),
 ("US-17","E5","Export reports",
  "As an authorized user, I want to export a report so that I can share or print it.",
  ["Report can be exported in a supported file format (PDF or CSV)",
   "Exported file matches the on-screen report"],
  3,"Medium",3,"FR-12","UC-07"),
 ("US-18","E6","Manage user accounts",
  "As an Administrator, I want to add, update and deactivate student and teacher accounts so that access stays current.",
  ["Administrator can add and update Student and Teacher accounts",
   "A deactivated account cannot log in"],
  5,"Medium",2,"FR-07",""),
 ("US-19","E6","Manage classes and subjects",
  "As an Administrator, I want to create classes and subjects and assign teachers so that attendance can be marked. (Pulled into Sprint 1 because marking depends on it.)",
  ["Administrator can create and edit classes and subjects",
   "Teachers can be assigned to classes and subjects"],
  5,"Medium",1,"FR-08",""),
 ("US-20","E6","Enroll students in classes and subjects",
  "As an Administrator, I want to assign students to classes and subjects so that rosters are correct.",
  ["Students can be assigned to classes and subjects",
   "The roster in UC-02 shows the enrolled students"],
  3,"Medium",1,"FR-09",""),
 ("US-21","E7","See a role-based dashboard summary",
  "As a user, I want a dashboard with the attendance information relevant to my role so that I see what matters first.",
  ["Student sees own attendance summary",
   "Teacher sees summary of assigned classes",
   "Administrator sees system-wide counts"],
  5,"Low",3,"FR-14",""),
 ("US-22","E8","Pages load within 3 seconds",
  "As a user, I want pages and attendance data to load quickly so that I can work without waiting.",
  ["Major pages load within 3 seconds under normal conditions",
   "Percentage and report queries use indexed lookups"],
  3,"High",3,"NFR-02","UC-05, UC-07"),
 ("US-23","E8","Back up attendance data regularly",
  "As an Administrator, I want regular backups so that saved attendance is never lost.",
  ["Backups run on a set schedule",
   "A backup can be restored in a test"],
  3,"High",3,"NFR-03","UC-04"),
 ("US-24","E8","Protect data in transit",
  "As a user, I want my data encrypted while it travels so that others cannot read it.",
  ["All pages and API calls use HTTPS",
   "Credentials are never sent over plain HTTP"],
  2,"High",2,"NFR-01",""),
 ("US-25","E8","Consistent, easy-to-use interface",
  "As a user, I want a clear and consistent interface so that I can find major functions easily.",
  ["Navigation and layout are consistent across pages",
   "Main tasks can be reached in a few clicks"],
  3,"Medium",3,"NFR-04",""),
 ("US-26","E8","Work on modern browsers",
  "As a user, I want the system to work in common browsers so that I can use my own device.",
  ["Works correctly in current Chrome, Edge and Firefox"],
  2,"Medium",3,"NFR-05",""),
]

PRIORITY_COLORS = {"High": "B60205", "Medium": "FBCA04", "Low": "0E8A16"}
POINTS = sorted({s[5] for s in STORIES})
